// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// Temporary removal of types import until types are regenerated

const SUPABASE_URL = 'https://svxcvsrvqhpuadhfeyen.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2eGN2c3J2cWhwdWFkaGZleWVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMzI0NTQsImV4cCI6MjA3MjkwODQ1NH0.tHWD8kA0WNAplP-bi-YNY9qNYn78QPhooLHE2G5V_g0';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});